export const CONNECT_PROVIDER = 'CONNECT_PROVIDER';
export const CONNECT_PROVIDER_SUCCESS = 'CONNECT_PROVIDER_SUCCESS';
export const CONNECT_PROVIDER_FAILURE = 'CONNECT_PROVIDER_FAILURE';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_FINISHED = 'LOGIN_FINISHED';
export const SET_USER_FUNDING_STATUS = 'SET_USER_FUNDING_STATUS';
