export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILURE = 'GET_PROJECT_FAILURE';

export const PROJECT_ADD_QUESTION_REQUEST = 'PROJECT_ADD_QUESTION_REQUEST';
export const PROJECT_ADD_QUESTION_SUCCESS = 'PROJECT_ADD_QUESTION_SUCCESS';
export const PROJECT_ADD_QUESTION_FAILURE = 'PROJECT_ADD_QUESTION_FAILURE';
export const PROJECT_ADD_QUESTION_RESET = 'PROJECT_ADD_QUESTION_RESET';

export const PROJECT_ADD_CHANGE_REQUEST = 'PROJECT_ADD_CHANGE_REQUEST';
export const PROJECT_ADD_CHANGE_SUCCESS = 'PROJECT_ADD_CHANGE_SUCCESS';
export const PROJECT_ADD_CHANGE_FAILURE = 'PROJECT_ADD_CHANGE_FAILURE';
export const PROJECT_ADD_CHANGE_RESET = 'PROJECT_ADD_CHANGE_RESET';

export const PROJECT_WITHDRAW_RESET = 'PROJECT_WITHDRAW_RESET';
