export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILURE = 'GET_PROJECT_FAILURE';

export const GET_ALL_PROJECTS_REQUEST = 'GET_ALL_PROJECTS_REQUEST';
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS';
export const GET_ALL_PROJECTS_FAILURE = 'GET_ALL_PROJECTS_FAILURE';

export const PROJECT_ADD_QUESTION_REQUEST = 'PROJECT_ADD_QUESTION_REQUEST';
export const PROJECT_ADD_QUESTION_SUCCESS = 'PROJECT_ADD_QUESTION_SUCCESS';
export const PROJECT_ADD_QUESTION_FAILURE = 'PROJECT_ADD_QUESTION_FAILURE';
export const PROJECT_ADD_QUESTION_RESET = 'PROJECT_ADD_QUESTION_RESET';

export const PROJECT_ADD_CHANGE_REQUEST = 'PROJECT_ADD_CHANGE_REQUEST';
export const PROJECT_ADD_CHANGE_SUCCESS = 'PROJECT_ADD_CHANGE_SUCCESS';
export const PROJECT_ADD_CHANGE_FAILURE = 'PROJECT_ADD_CHANGE_FAILURE';
export const PROJECT_ADD_CHANGE_RESET = 'PROJECT_ADD_CHANGE_RESET';

export const PROJECT_WITHDRAW_REQUEST = 'PROJECT_WITHDRAW_REQUEST';
export const PROJECT_WITHDRAW_SUCCESS = 'PROJECT_WITHDRAW_SUCCESS';
export const PROJECT_WITHDRAW_FAILURE = 'PROJECT_WITHDRAW_FAILURE';
export const PROJECT_WITHDRAW_RESET = 'PROJECT_WITHDRAW_RESET';

export const PROJECT_FUND_REQUEST = 'PROJECT_FUND_REQUEST';
export const PROJECT_FUND_SUCCESS = 'PROJECT_FUND_SUCCESS';
export const PROJECT_FUND_FAILURE = 'PROJECT_FUND_FAILURE';
export const PROJECT_FUND_RESET = 'PROJECT_FUND_RESET';

export const PROJECT_WITHDRAW_HISTORY_REQUEST = 'PROJECT_WITHDRAW_HISTORY_REQUEST';
export const PROJECT_WITHDRAW_HISTORY_SUCCESS = 'PROJECT_WITHDRAW_HISTORY_SUCCESS';
export const PROJECT_WITHDRAW_HISTORY_FAILURE = 'PROJECT_WITHDRAW_HISTORY_FAILURE';

export const PROJECT_ADD_PROPOSAL_REQUEST = 'PROJECT_ADD_PROPOSAL_REQUEST';
export const PROJECT_ADD_PROPOSAL_SUCCESS = 'PROJECT_ADD_PROPOSAL_SUCCESS';
export const PROJECT_ADD_PROPOSAL_FAILURE = 'PROJECT_ADD_PROPOSAL_FAILURE';
export const PROJECT_ADD_PROPOSAL_RESET = 'PROJECT_ADD_PROPOSAL_RESET';

export const GET_PROJECT_PROPOSALS_REQUEST = 'GET_PROJECT_PROPOSALS_REQUEST';
export const GET_PROJECT_PROPOSALS_SUCCESS = 'GET_PROJECT_PROPOSALS_SUCCESS';
export const GET_PROJECT_PROPOSALS_FAILURE = 'GET_PROJECT_PROPOSALS_FAILURE';

export const SUPPORT_PROPOSAL_REQUEST = 'SUPPORT_PROPOSAL_REQUEST';
export const SUPPORT_PROPOSAL_SUCCESS = 'SUPPORT_PROPOSAL_SUCCESS';
export const SUPPORT_PROPOSAL_FAILURE = 'SUPPORT_PROPOSAL_FAILURE';

export const DECLINE_PROPOSAL_REQUEST = 'DECLINE_PROPOSAL_REQUEST';
export const DECLINE_PROPOSAL_SUCCESS = 'DECLINE_PROPOSAL_SUCCESS';
export const DECLINE_PROPOSAL_FAILURE = 'DECLINE_PROPOSAL_FAILURE';
