export const START_PROJECT_REQUEST = 'START_PROJECT_REQUEST';
export const START_PROJECT_SUCCESS = 'START_PROJECT_SUCCESS';
export const START_PROJECT_FAILURE = 'START_PROJECT_FAILURE';

export const START_PROJECT_RESET = 'START_PROJECT_RESET';
